[tool.poetry]
name = "potatoNews"
version = "0.1.1"
description = ""
authors = ["pnv28 <pnv28@duck.com>"]

[tool.poetry.dependencies]
python = "^3.10"
py-cord = "2.5.0"
requests = "2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
